
name: Build & Deploy

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Installing packages
        run: npm install

      - name: Build Gridsome site
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BASE_BRANCH: master
          BRANCH: master
          FOLDER: dist
          external_repository: AramDonyaee/aramdonyaee.github.io
          user_name: adonyaee
          user_email: adonyaee@yahoo.com
