
name: Build and Deploy

on: push
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Installing packages
        run: npm install

      - name: Build Gridsome site
        run: yarn build

      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: AramDonyaee/aramdonyaee.github.io
          publish_dir: dist
          user_name: adonyaee
          user_email: adonyaee@yahoo.com
          publish_branch: master
